_SUPPORTED = not host_info().os.is_windows

# buildifier: disable=no-effect
ocaml_binary(
    name = "hello-world",
    srcs = ["hello_world.ml"],
    deps = [":hello-world-lib"],
) if _SUPPORTED else None

# buildifier: disable=no-effect
ocaml_library(
    name = "hello-world-lib",
    srcs = ["hello_world_lib.ml"],
    visibility = ["PUBLIC"],
) if _SUPPORTED else None
