ocaml_binary(
    name = "extra-test",
    srcs = ["test.ml"],
    deps = [
        "extra//extra-lib:extra",
        "extra//third-party/ocaml:ounit2",
        "extra//third-party/ocaml:unix",
    ],
)
