name: Buck build and test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  buck-build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: facebook/install-dotslash@latest
      - run: sudo apt-get update && sudo apt-get install opam libzstd-dev
        if: matrix.os == 'ubuntu'
      - run: brew install opam zstd coreutils
        if: matrix.os == 'macos'
      - run: |
          opam init --color=always --compiler=5.1.1 --disable-sandboxing -y
          opam install --color=always menhir ppxlib ounit core -y
          opam env | sed -e "s/ export .*//g" -e "s/'//g" -e "s/\;//g" >> $GITHUB_ENV
      - run: ./ocaml-setup.sh
      - run: ./buck2 build extra//... -v 2
      - run: ./buck2 run extra//extra-test:extra-test -v 2 -- -ci true
      - run: ./buck2 run extra//sort-test:sort-test -v 2 -- -ci true
      - run: ./buck2 run extra//core-test:hello-core -v 2
