name: Buck build and test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  buck-build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install-buck2@latest
        with:
          prelude-submodule: prelude
      - run: sudo apt-get update && sudo apt-get install opam
        if: matrix.os == 'ubuntu'
      - run: brew install opam
        if: matrix.os == 'macos'
      - run: |
          opam init --compiler=5.1.1 --disable-sandboxing -y
          opam install menhir ppxlib -y
          opam env | sed -e "s/ export .*//g" -e "s/'//g" -e "s/\;//g" >> $GITHUB_ENV
      - run: ./ocaml-setup.sh
      - run: buck2 build root//... -v 2
